### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by chadsaun** [svgdotjs/svg.filter.js#26]
I use Webpack and it would be great if I could import this into my project.

**Comment by rdfriedl** [comment]
to use `svg.js` and `svg.filter.js` in webpack should be as simple as importing the libraries.
```js
import * as SVG from "svg.js";
import "svg.filter.js";
```

see an example here https://codesandbox.io/s/91km65yk2o

the only catch to this is that if you `import` svg.js you can no longer do 
`var draw = new SVG("someElement");`
instead you have to use 
`var draw = new SVG.Doc("someElement");`

**Comment by chadsaun** [comment]
Oh thank you!

One other question though.  Using your example, [why doesn't adding `draw.clear()` work](https://codesandbox.io/embed/1op0xy1ymj)?

**Comment by Garviell** [comment]
> to use `svg.js` and `svg.filter.js` in webpack should be as simple as importing the libraries.
> 
> ```js
> import * as SVG from "svg.js";
> import "svg.filter.js";
> ```
> 
> see an example here https://codesandbox.io/s/91km65yk2o
> 
> the only catch to this is that if you `import` svg.js you can no longer do
> `var draw = new SVG("someElement");`
> instead you have to use
> `var draw = new SVG.Doc("someElement");`

You should add a link to this in the readme.  There is another package called svg-filter which causes some confusion if you go onto npm and just look for this.

https://www.npmjs.com/package/svg.filter.js

**Comment by Fuzzyma** [comment]
Please go over to stackoverflow or the chat for questions. Also don't reuse old issues!

You have to use `filterWith()` and not `filter()`

**Comment by Rubinhuang9239** [comment]
@Fuzzyma Thanks you.
I can see the reason why I have post the question: the example of `Drop Shadow` in readme are outdated and still using `filter()`. However, I still get `e.draw.circle(...).filterWith is not a function` error.

Willing get it work so I can maybe make a PR to update the readme.

**Comment by Fuzzyma** [comment]
How did you load the plugin? Head over to https://gitter.im/svgdotjs/svg.js for better support
