### ISSUE TITLE
Upgrade to 3.0.2 SVG is not defined

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.filter.js#30]

**Comment by PiotrFr** [comment]
I am trying to upgrade my program and replace version 2.0.2 with version 3.0.2. 

package.json
```
  "dependencies": {
....
    "@svgdotjs/svg.js": "^3.0.11",
    "@svgdotjs/svg.filter.js": "^3.0.2",
```

xxxxx.service.ts
```
//import "svg.js"  //v 2.7
import SVG from "@svgdotjs/svg.js/src/svg"   //v 3.0

//import "svg.filter.js"  //v 2.0
import "@svgdotjs/svg.filter.js"  //3.0.2

//declare const SVG: any    //v 2.7
```



**ReferenceError: SVG is not defined**
```
    at Object../node_modules/@svgdotjs/svg.filter.js/dist/svg.filter.min.js (c:\Users\piotrf\pro\aproj01\node_modules\@svgdotjs\svg.filter.js\dist\svg.filter.min.js:2:8663)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/app/dzielo-svg.service.ts (http://localhost:4200/main.js:1201:81)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/app/dzielo.service.ts (http://localhost:4200/main.js:1984:77)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/app/app.component.ts (http://localhost:4200/main.js:134:73)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/app/app.module.ts (http://localhost:4200/main.js:210:72)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
```

**Comment by Fuzzyma** [comment]
It seems like webpack uses the wrong file. As you can see in the package.json, the `module` key links to `src/svg.filter.js` which is the correct file. Can you configure webpack in a way, that it uses the right file?

**Comment by Fuzzyma** [comment]
If not, you may specify it like with svg.js: `@svgdotjs/svg.filter.js/src/svg.filter.js`

**Comment by Fuzzyma** [comment]
I am pretty sure you can tell webpack somehow to resolve this package to the correct file. Please try that. I cannot see a mistake on our site (not seeing doesn't imply it's not there - so if you find the mistake please report it!)

**Comment by PiotrFr** [comment]
See https://github.com/svgdotjs/svg.js/issues/952. Maybe it's the same problem.

With new project
app.component.ts
```
import { Component } from '@angular/core';
import SVG from "@svgdotjs/svg.js/src/svg"   //v 3.0

import "@svgdotjs/svg.filter.js/dist/svg.filter.js"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'zmaz01';
}

```
I get the same error.
```
Uncaught ReferenceError: SVG is not defined
    at Object../node_modules/@svgdotjs/svg.filter.js/dist/svg.filter.js (svg.filter.js:597)
```

**Comment by Fuzzyma** [comment]
You can work around your issue by doing it like your linked issue. But than you have a global SVG which might be not what you want.

Ofc you get that error again. As I said, the correct file for esm imports is in `src/`. This is also correctly specified in the package.json. Obviously your webpack loads the wrong file anyway. So you need to tell webpack to load the correct file

**Comment by PiotrFr** [comment]
Thank you for your patience :)
In my  node_modules I do not find src
![image](https://user-images.githubusercontent.com/13883511/52235746-4d2d6600-28c5-11e9-8dcf-30573c5df412.png)


I copy it from GIT and I get now 
```
svg.filter.js:14 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Module../node_modules/@svgdotjs/svg.filter.js/src/svg.filter.js (svg.filter.js:14)
```

**Comment by Fuzzyma** [comment]
aiaiai - I guess you found the issue. There was a `files` key in package.json and it only specified `dist`. So the src folder wasnt up/downloaded from npm. I fixed that and released a new version. Can you try it now?

**Comment by PiotrFr** [comment]
now
![image](https://user-images.githubusercontent.com/13883511/52253410-fa28d280-2907-11e9-89d7-d7422019f2e0.png)

but with 
`import "@svgdotjs/svg.filter.js/src/svg.filter.js"`
```
svg.filter.js:14 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Module../node_modules/@svgdotjs/svg.filter.js/src/svg.filter.js (svg.filter.js:14)
```

and  with 
`import "@svgdotjs/svg.filter.js"`
```
svg.filter.min.js:2 Uncaught ReferenceError: SVG is not defined
    at Object../node_modules/@svgdotjs/svg.filter.js/dist/svg.filter.min.js (svg.filter.min.js:2)
```

**Comment by Fuzzyma** [comment]
Sorry for the delay. I am just unsure what to do from here. It seems like it is loading the correct file now but some object which the filter extends is not defined (yet). Can you post a minimal package.json and webpack conf so that I can test that myself?

**Comment by PiotrFr** [comment]
I am using Angular CLI.
1. A new project
2. In package.json add to "dependencies"
```
"@svgdotjs / svg.filter.js": "^ 3.0.3",
"@ svgdotjs / svg.js": "^ 3.0.11",
```
3. In app.components.ts
```
import SVG from "@ svgdotjs / svg.js / src / svg" // v 3.0
import "@ svgdotjs / svg.filter.js / src / svg.filter.js"
```

I do not have experience with other tools :(

**Comment by PiotrFr** [comment]
With (in package.json) 
```
"@svgdotjs/svg.filter.js": "^3.0.4",
"@svgdotjs/svg.js": "^3.0.12",
```
is OK.
