### ISSUE TITLE
offset change in v3.0 x, y not dx, dy

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.filter.js#33]
Function offset change in new version (3) parameter x, y not dx, dy.

**Comment by Fuzzyma** [comment]
Please elaborate further!

**Comment by PiotrFr** [comment]
With
```
      awers.filterWith(function (add) {
       var blur = add.offset(10, 10).in(add.$sourceAlpha).gaussianBlur(5)  //v 2.7 <======
      //  var blur = add.dropShadow(add.$sourceAlpha,10,10).gaussianBlur(5)  //v 3.0
        add.blend(add.$source, blur)  
        this.size('200%', '200%').move('-50%', '-50%') //?
      })
```
I get 
`<filter width="200%" height="200%" x="-50%" y="-50%" id="SvgjsFilter1017">
       <feOffset id="SvgjsFeOffset1014" result="SvgjsFeOffset1014" in="SourceAlpha" y="10" x="10"></feOffset>
.......
</filter>`

not dy ="10" dx="10"

**Comment by Fuzzyma** [comment]
Is only `offset` broken or dropShadow, too?

**Comment by PiotrFr** [comment]
Only offset. I use now (v 3.0) dropShadow  because of this problem.

**Comment by Fuzzyma** [comment]
fixed: https://github.com/svgdotjs/svg.filter.js/releases/tag/3.0.5
