### ISSUE TITLE
How do you change the opacity or colour of a drop shadow/gaussian blur?

### ISSUE THREAD

**Issue by nmg196** [svgdotjs/svg.filter.js#45]
How do you change the opacity or colour of a drop shadow/gaussian blur?

The default looks too dark and the object doesn't seem to allow .opacity() on it.

See: https://jsfiddle.net/nmg196/b75em12L/2/

**Comment by Fuzzyma** [comment]
Use a shape with a different color as input for the filter. svg filters work with what you give them.
Gaussian blur will blur whatever you input. So if you want a lighter blur, you need to input a lighter shape. Unfortunetaly I cannot give you an example here because I dont use filter quite often.

**Comment by Outcue** [comment]
You can add a flood color to the filter and composite it with the blur.

Use something like this as a starting point:

```
const blur = add
        .flood('#000000', 0.3)
        .composite(add.$source, 'in')
        .gaussianBlur(10.0, 10.0)
        .offset(10.0, 10.0)
add.blend(add.$source, blur, null)
```
