### ISSUE TITLE
Are there any possible ways to sharpen an image?

### ISSUE THREAD

**Issue by pycraft114** [svgdotjs/svg.filter.js#46]
changing brightness and contrast of an image were available by using this library but is it also possible to sharpen an image?

**Comment by Fuzzyma** [comment]
You could try this one here: https://webplatform.github.io/docs/svg/tutorials/smarter_svg_filters/#Sharpening-images-with-feConvolveMatrix

**Comment by pycraft114** [comment]
@Fuzzyma Big thx for the reference! :)
