### ISSUE TITLE
Is there a way to use this plugin through a CDN?

### ISSUE THREAD

**Issue by RichardJECooke** [svgdotjs/svg.filter.js#60]
I don't want to install node and yarn and npm just to draw a picture. 

Is there a way to use this library by importing a file by please?

Like I can use SVG.js by going: `<script src="https://cdn.jsdelivr.net/npm/@svgdotjs/svg.js@3.0/dist/svg.min.js"></script>` and I'm ready to go.

**Comment by wout** [comment]
Of course: https://cdnjs.com/libraries/svg.js

It's also described here: https://svgjs.dev/docs/3.0/installation/

**Comment by RichardJECooke** [comment]
Thank you! Please add this to your documtenation on your new website too. Looking forward to seeing that.

**Comment by RichardJECooke** [comment]
Sorry no, where is the `filter.js` file on this site?

**Comment by Fuzzyma** [comment]
@RichardJECooke i guess you are looking for this: https://unpkg.com/@svgdotjs/svg.filter.js@3.0.8/dist/svg.filter.min.js

Most packages from npm can be pulled from unpkg if you need them :)

**Comment by wout** [comment]
Exactly. I was about to say the same :)

**Comment by RichardJECooke** [comment]
Ah, thanks.

**Comment by jimaek** [comment]
Btw since you already use jsDelivr can continue to do so https://cdn.jsdelivr.net/npm/@svgdotjs/svg.filter.js@3.0.8/dist/svg.filter.min.js
