### ISSUE TITLE
Typo in distantLight effect.

### ISSUE THREAD

**Issue by sqwarellc** [svgdotjs/svg.filter.js#61]
In multiple places in the source file svg.filter.js.d.ts, the effect distantLight is spelled "distandLight". Just something I stumbled across while reading a Q&A thread where someone couldn't find it and was trying to create it separately. Probably best to keep it (for code compatibility for anyone who has used it with that spelling) and add the correct definition as well for future use.

**Comment by Fuzzyma** [comment]
The actual js file seems to be correct. So if only the typings are wrong I am all for fixing the spelling. If anyone used the wrong spelling, they will have non-functioning code (svg.filter.js.d.ts are only the types and not the actual code). Feel free to create a PR to fix that mistake and thanks for reporting!! :)

**Comment by sqwarellc** [comment]
Thanks for the reply. I am new to GitHub (and JavaScript development for that matter) so I probably shouldn't be the one doing the correction at this stage until I have more experience.

**Comment by Fuzzyma** [comment]
>Thanks for the reply. I am new to GitHub (and JavaScript development for that matter) so I probably shouldn't be the one doing the correction at this stage until I have more experience.

This is a rather safe and small change so I actually think it would be perfect to learn your way around github :).
For this small change you can even do the change directly on github (open svg.filter.js.d.ts and click on the little pencil icon to edit it). The github UI should then offer you to fork the repo, commit the change and create a PR from it. You cannot break anything. So if you want, give it a try :)

**Comment by sqwarellc** [comment]
Done. I hope I did that correctly. :-)

I am going to ask a neophyte question in another issue, I hope you have time to answer. Thanks.

**Comment by Fuzzyma** [comment]
Thank you very much! :)
